targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true 
          explicit_to_json: true
          field_rename: snake
      freezed:
        generate_for:
          include:
            - lib/feature/github_repo/model/*.dart
            - lib/core/model/*.dart
            - lib/core/services/model/**/*.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
