targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true 
          explicit_to_json: true
          field_rename: snake
      freezed:
        generate_for:
          include:
            - lib/feature/github_repo/model/*.dart
