name: github_repo_search
description: A Flutter app to search GitHub repositories.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Logger
  simple_logger: ^1.9.0

  # freezed
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: ^1.19.2
  flutter_lints: ^2.0.0

  # Serializer
  json_serializable: ^6.3.1

  # Code generator
  build_runner: ^2.2.0
  freezed: ^2.1.0+1


flutter:

  uses-material-design: true
