name: github_repo_search
description: A Flutter app to search GitHub repositories.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.5
  json_annotation: ^4.6.0
  simple_logger: ^1.9.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
