name: github_repo_search
description: A Flutter app to search GitHub repositories.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  extended_image: ^6.2.1
  fast_i18n: ^5.12.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter         
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pull_to_refresh_flutter3: ^2.0.1
  shared_preferences: ^2.0.15
  simple_logger: ^1.9.0
  slang: ^2.7.0
  slang_flutter: ^2.7.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  pedantic_mono: ^1.19.2
  slang_build_runner: ^2.7.0

# flutter gen
flutter_gen:
  output: lib/gen/
  colors:
    inputs:
      - assets/color/color.xml

flutter_icons:
   android: true
   ios: true
   image_path: 'assets/images/icon.png'
   adaptive_icon_background: '#fcf4ec'
   adaptive_icon_foreground: 'assets/images/icon_adaptive.png'

flutter_native_splash:
  color: '#fcf4ec'
  image: 'assets/images/splash_image.png'
  color_dark: '#262626'
  image_dark: 'assets/images/splash_image.png'
  android_12:
    icon_background_color: '#fcf4ec'
    image: 'assets/images/splash_image_android.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/splash_image_android.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/not_found.png

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 900
